[build]
  # Directory to change to for package.json before starting a build.
  base = "/"

  # Directory that contains the deploy-ready HTML files
  publish = "/public/"

  # Default build command.
  command = "npm run build"

  # Netlify functions
  functions = "functions/"

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/data"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}