[build]
  # Directory to change to for package.json before starting a build.
  base = "/"

  # Directory that contains the deploy-ready HTML files
  publish = "/public/"

  # Default build command.
  command = "npm run build"

[[redirects]]
  from = "/api/"
  to = "https://brianmooremusic-data.netlify.app/api/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/media/*"
  to = "https://brianmooremusic-data.netlify.app/media/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  